name: dxlibv3_dart
description: A starting point for Dart libraries or applications.
version: 2.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  pinenacl: ^0.6.0
  cryptography: ^2.7.0
  http: ^1.3.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
